name: bloc_todo
description: A new Flutter application to learn BLoC patterns
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  uuid: ^2.0.4
  provider: ^4.0.4
  equatable: ^1.0.0
  flutter_bloc: ^3.2.0
  path_provider: ^1.6.5
  stream_transform: ^1.2.0
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  google_sign_in: ^4.3.0
  font_awesome_flutter: ^8.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.9

flutter:
  uses-material-design: true
  assets:
    - images/
flutter_intl:
  enabled: true
